version: "3"

services:
  authenticator:
    build: .
    command: npm run dev
    ports:
      - 3001:3001
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: authenticator
      POSTGRES_PASSWORD: authenticator
      POSTGRES_DB: authenticator
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "4321:5432"
